import Ember from 'ember';

var settingsService = Ember.Service.extend({
  store: Ember.inject.service('store'),
  cognito: Ember.inject.service('cognito'),
  setup: function() {
    var settings = this;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      settings.get("store").findAll("setting").then(function(model) {
        model.forEach(function(item) {
          settings.set(item.get("id"), item.get("value"));
        });
        resolve();
      });
    });
  },
  reloadAllSettings: function(data) {
    for(var i in data) {
      if(data.hasOwnProperty(i)) {
        this.save(i, data[i], false);
      }
    }
  },
  load: function(name) {
    var localVal, val;
    localVal = this.get(name);
    val = this.get(name);
    if (!val) {
      var setting = this.get("store").peekRecord("setting", name);
      if (setting !== null) {
        val = setting.get("value");
      }
    }

    //todo: Replace this with code/service for Amazon.
    //Loads via Cognito are async, which makes this mostly impossible.
    //What happens instead is that every time a setting is saved the whole mess
    //is synced and the settings object is updated as a lump. This also happens
    //on app startup, and login. So we shouldn't need to access the cognito
    //settings object directly from here.


    if(localVal !== val) {
      this.set(name, val);
    }

    return val;
  },
  save: function(name, value, sync) {
    var setting = this.get("store").peekRecord("setting", name);
    if (setting === null) {
      setting = this.get("store").createRecord("setting", {id: name, 'value': value});
    } else {
      setting.set("value", value);
    }
    setting.save();

    if (sync !== false) {
      //Save to Cognito
      this.get("cognito").putSetting(name, value);
    }

    //This is to trigger observable changes, otherwise they aren't triggered
    this.set(name, null);
    this.set(name, value);
  },
  /**
   * This function is a method of making settings visible app-wide
   * without persisting them. It is used to store things that will
   * be generated by using the app each time but that need to be
   * shared between controllers. Eg visibility of items, page titles etc.
   * @param name
   * @param value
   */
  setSessionVar: function(name, value) {
    this.set(name, value);
  }
});

export default settingsService;

